///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsFacebook = 'assets/icons/facebook.png';
  static const String iconsGoogle = 'assets/icons/google.png';
  static const String iconsHome = 'assets/icons/home.png';
  static const String iconsSettings = 'assets/icons/settings.png';
  static const String iconsShop = 'assets/icons/shop.png';
  static const String iconsTwitter = 'assets/icons/twitter.png';
  static const String iconsUser = 'assets/icons/user.png';
  static const String imagesLagan1 = 'assets/images/lagan1.png';
  static const String imagesLagan2 = 'assets/images/lagan2.png';
  static const String imagesLagan3 = 'assets/images/lagan3.png';
  static const String imagesOnboard1 = 'assets/images/onboard1.png';
  static const String imagesOnboard2 = 'assets/images/onboard2.png';

}
